#pragma once 
#include "KeyValue.idl"

module diagnostic_msgs
{

    const char OK       = 0;
    const char WARN     = 1;
    const char ERROR    = 2;
    const char STALE    = 3;
    struct DiagnosticStatus {
        char level;
        string name;
        string message;
        string hardware_id;
        sequence<diagnostic_msgs::KeyValue> values;
    };
};