#include "geometry_msgs/msg/Accel.idl"
#include "geometry_msgs/msg/AccelStamped.idl"
#include "geometry_msgs/msg/AccelWithCovariance.idl"
#include "geometry_msgs/msg/AccelWithCovarianceStamped.idl"
#include "geometry_msgs/msg/Inertia.idl"
#include "geometry_msgs/msg/InertiaStamped.idl"
#include "geometry_msgs/msg/Point.idl"
#include "geometry_msgs/msg/Point32.idl"
#include "geometry_msgs/msg/PointStamped.idl"
#include "geometry_msgs/msg/Polygon.idl"
#include "geometry_msgs/msg/PolygonInstance.idl"
#include "geometry_msgs/msg/PolygonInstanceStamped.idl"
#include "geometry_msgs/msg/PolygonStamped.idl"
#include "geometry_msgs/msg/Pose.idl"
#include "geometry_msgs/msg/Pose2D.idl"
#include "geometry_msgs/msg/PoseArray.idl"
#include "geometry_msgs/msg/PoseStamped.idl"
#include "geometry_msgs/msg/PoseWithCovariance.idl"
#include "geometry_msgs/msg/PoseWithCovarianceStamped.idl"
#include "geometry_msgs/msg/Quaternion.idl"
#include "geometry_msgs/msg/QuaternionStamped.idl"
#include "geometry_msgs/msg/Transform.idl"
#include "geometry_msgs/msg/TransformStamped.idl"
#include "geometry_msgs/msg/Twist.idl"
#include "geometry_msgs/msg/TwistStamped.idl"
#include "geometry_msgs/msg/TwistWithCovariance.idl"
#include "geometry_msgs/msg/TwistWithCovarianceStamped.idl"
#include "geometry_msgs/msg/Vector3.idl"
#include "geometry_msgs/msg/Vector3Stamped.idl"
#include "geometry_msgs/msg/VelocityStamped.idl"
#include "geometry_msgs/msg/Wrench.idl"
#include "geometry_msgs/msg/WrenchStamped.idl"