#pragma once
#include "sensor_msgs/BatteryState.idl"
#include "sensor_msgs/ChannelFloat32.idl"
#include "sensor_msgs/Image.idl"
#include "sensor_msgs/Imu.idl"
#include "sensor_msgs/JointState.idl"
#include "sensor_msgs/Joy.idl"
#include "sensor_msgs/JoyFeedback.idl"
#include "sensor_msgs/JoyFeedbackArray.idl"
#include "sensor_msgs/LaserEcho.idl"
#include "sensor_msgs/LaserScan.idl"
#include "sensor_msgs/PointCloud.idl"
#include "sensor_msgs/PointCloud2.idl"
#include "sensor_msgs/PointField.idl"
#include "sensor_msgs/Temperature.idl"
#include "sensor_msgs/MultiDOFJointState.idl"
#include "sensor_msgs/MultiEchoLaserScan.idl"
#include "sensor_msgs/Range.idl"
#include "sensor_msgs/RegionOfInterest.idl"
#include "sensor_msgs/CameraInfo.idl"
#include "sensor_msgs/CompressedImage.idl"