#include "std_msgs/msg/Bool.idl"
#include "std_msgs/msg/Byte.idl"
#include "std_msgs/msg/ByteMultiArray.idl"
#include "std_msgs/msg/Char.idl"
#include "std_msgs/msg/ColorRGBA.idl"
#include "std_msgs/msg/Empty.idl"
#include "std_msgs/msg/Float32.idl"
#include "std_msgs/msg/Float32MultiArray.idl"
#include "std_msgs/msg/Float64.idl"
#include "std_msgs/msg/Float64MultiArray.idl"
#include "std_msgs/msg/Header.idl"
#include "std_msgs/msg/Int16.idl"
#include "std_msgs/msg/Int16MultiArray.idl"
#include "std_msgs/msg/Int32.idl"
#include "std_msgs/msg/Int32MultiArray.idl"
#include "std_msgs/msg/Int64.idl"
#include "std_msgs/msg/Int64MultiArray.idl"
#include "std_msgs/msg/Int8.idl"
#include "std_msgs/msg/Int8MultiArray.idl"
#include "std_msgs/msg/MultiArrayDimension.idl"
#include "std_msgs/msg/MultiArrayLayout.idl"
#include "std_msgs/msg/String.idl"
#include "std_msgs/msg/UInt16.idl"
#include "std_msgs/msg/UInt16MultiArray.idl"
#include "std_msgs/msg/UInt32.idl"
#include "std_msgs/msg/UInt32MultiArray.idl"
#include "std_msgs/msg/UInt64.idl"
#include "std_msgs/msg/UInt64MultiArray.idl"
#include "std_msgs/msg/UInt8.idl"
#include "std_msgs/msg/UInt8MultiArray.idl"