//  This message contains an uncompressed image
//  (0, 0) is at top-left corner of image

#include "std_msgs.idl"

module sensor_msgs {
    struct Image {
        std_msgs::Header _header;       // Header timestamp should be acquisition time of image
                                        // Header frame_id should be optical frame of camera
                                        // origin of frame should be optical center of camera
                                        // +x should point to the right in the image
                                        // +y should point down in the image
                                        // +z should point into the plane of the image
                                        // If the frame_id here and the frame_id of the CameraInfo
                                        // message associated with the image conflict
                                        // the behavior is undefined
        unsigned long height;           // image height, that is, number of rows
        unsigned long width;            // image width, that is, number of columns
        string  encoding;               // Encoding of pixels -- channel meaning, ordering, size
                                        // taken from the list of strings in include/sensor_msgs/image_encodings.hpp
        octet   is_bigendian;           // is this data bigendian?
        unsigned long step;             // Full row length in bytes
        sequence<octet> data;           // actual matrix data, size is (step * rows)
    };
};