#pragma once
#include "std_msgs.idl"
module sensor_msgs
{
    //# The timestamp is the time at which data is received from the joystick.
    struct Joy
    {

        std_msgs::Header _header;
        sequence<float> axes; //# The axes measurements from a joystick.
        sequence<long> buttons; //# The buttons measurements from a joystick.
    };
};