#pragma once
#include "std_msgs.idl"
#include "JoyFeedback.idl"
module sensor_msgs
{
    // ##########################################################################
    // # Array of JoyFeedback commands, to be sent as a single update.
    struct JoyFeedbackArray
    {
        sequence<sensor_msgs::JoyFeedback> array;  // # List of feedback commands.
    };
};