#pragma once
#include "std_msgs.idl"
module sensor_msgs
{
    struct Temperature
    {

        std_msgs::Header _header;   // timestamp is the time the temperature was measured
                                    // frame_id is the location of the temperature reading

        double temperature;         // Measurement of the Temperature in Degrees Celsius.

        double variance;            // 0 is interpreted as variance unknown.
    };
};